export const CARDS = [
  // Positive
  {
    id: "wildThrees",
    name: "Wild 3s",
    description: "Your 3s act as the most common non-3 value in your roll.",
    type: "positive",
    effectKey: "wildThrees",
    color: "emerald",
  },
  {
    id: "luckySevens",
    name: "Lucky 7s",
    description: "All your 1s become 6s this turn.",
    type: "positive",
    effectKey: "luckySevens",
    color: "emerald",
  },
  {
    id: "mirrorImage",
    name: "Mirror Image",
    description: "2 random dice copy the value of your highest die.",
    type: "positive",
    effectKey: "mirrorImage",
    color: "blue",
  },
  {
    id: "extraRoll",
    name: "Extra Roll",
    description: "You get 4 rolls this turn instead of 3.",
    type: "positive",
    effectKey: "extraRoll",
    color: "emerald",
  },
  {
    id: "doubleDown",
    name: "Double Down",
    description: "Your committed score this turn is doubled.",
    type: "positive",
    effectKey: "doubleDown",
    color: "yellow",
  },
  {
    id: "steal",
    name: "Steal",
    description: "Copy any one already-scored category from an opponent.",
    type: "positive",
    effectKey: "steal",
    color: "purple",
  },
  {
    id: "swapDice",
    name: "Swap Dice",
    description: "Swap your current dice with another player's last roll.",
    type: "positive",
    effectKey: "swapDice",
    color: "blue",
  },
  // Negative
  {
    id: "fumble",
    name: "Fumble",
    description: "You cannot hold any dice — all 5 are rerolled every time.",
    type: "negative",
    effectKey: "fumble",
    color: "red",
  },
  {
    id: "halfScore",
    name: "Half Score",
    description: "Your committed score this turn is halved (rounded down).",
    type: "negative",
    effectKey: "halfScore",
    color: "red",
  },
  {
    id: "brokenDie",
    name: "Broken Die",
    description: "One random die gets stuck on whatever it first rolls — it can't be held or rerolled.",
    type: "negative",
    effectKey: "brokenDie",
    color: "red",
  },
  {
    id: "forcedCategory",
    name: "Forced Category",
    description: "You must score in a randomly chosen category this turn.",
    type: "negative",
    effectKey: "forcedCategory",
    color: "orange",
  },
  {
    id: "rewind",
    name: "Rewind",
    description: "You only get 1 roll this turn — no rerolls.",
    type: "negative",
    effectKey: "rewind",
    color: "red",
  },
  {
    id: "cursedSixes",
    name: "Cursed Sixes",
    description: "All your 6s count as 1s for scoring this turn.",
    type: "negative",
    effectKey: "cursedSixes",
    color: "red",
  },
];
